<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            ['name' => 'طبة', 'sku' => 'RAW-01', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 300],
            ['name' => 'لاكور ', 'sku' => 'RAW-02', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 300],
            ['name' => 'صامولة رشاش', 'sku' => 'RAW-03', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 300],
            ['name' => 'فونية 50', 'sku' => 'RAW-04', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فونية 60', 'sku' => 'RAW-05', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 200],
            ['name' => 'فونية 70', 'sku' => 'RAW-06', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فونية 80', 'sku' => 'RAW-07', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فونية 85', 'sku' => 'RAW-08', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فونية 90', 'sku' => 'RAW-09', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فونية 95', 'sku' => 'RAW-10', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ثلاثية كاملة', 'sku' => 'RAW-11', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 300],
            ['name' => 'نحاسة عين 50', 'sku' => 'RAW-12', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'نحاسة عين 60', 'sku' => 'RAW-13', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'نحاسة عين 70', 'sku' => 'RAW-14', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'المونية عين 50', 'sku' => 'RAW-15', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'المونية عين 60', 'sku' => 'RAW-16', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'المونية عين 70', 'sku' => 'RAW-17', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'صاجة عين 90(وسط) الترا', 'sku' => 'RAW-18', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'صاجة عين 50 مشرشر', 'sku' => 'RAW-19', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'صاجة عين 60 مشرشر', 'sku' => 'RAW-20', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'صاجة عين 70 مشرشر', 'sku' => 'RAW-21', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'المونية عين 50 مشرشر', 'sku' => 'RAW-22', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'المونية عين 60 مشرشر', 'sku' => 'RAW-23', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'المونية عين 70 مشرشر', 'sku' => 'RAW-24', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'المونية عين 90 مشرشر', 'sku' => 'RAW-25', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ضفيرة ديجيتال', 'sku' => 'RAW-26', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ضفيرة عادية', 'sku' => 'RAW-27', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'بطارية 6 طرف', 'sku' => 'RAW-28', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'كابل', 'sku' => 'RAW-29', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'سلك ارضي (بطارية)', 'sku' => 'RAW-30', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'تايمر ديجيتال', 'sku' => 'RAW-31', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'تايمر ميكانيكي', 'sku' => 'RAW-32', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'لمبة ', 'sku' => 'RAW-33', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شمعة اشعال', 'sku' => 'RAW-34', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'تيل شمعة اشعال', 'sku' => 'RAW-35', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 500],
            ['name' => 'وردة شمعة اشعال', 'sku' => 'RAW-36', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 500],
            ['name' => 'سوسته شمعة اشعال', 'sku' => 'RAW-37', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1],
            ['name' => 'سويتش اشعال', 'sku' => 'RAW-38', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'سويتش لمبة ومروحة وماتور', 'sku' => 'RAW-39', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'وش سويتش اشعال ', 'sku' => 'RAW-40', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'وش سويتش لمبة', 'sku' => 'RAW-41', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'وش سويتش ماتور ', 'sku' => 'RAW-42', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'وش سويتش مروحة', 'sku' => 'RAW-43', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شاسيه سويتش', 'sku' => 'RAW-44', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'اسورة(مفتاح)', 'sku' => 'RAW-45', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'مفتاح 90 هامر', 'sku' => 'RAW-46', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'سوسته مفتاح', 'sku' => 'RAW-47', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'صمام شواية طراش', 'sku' => 'RAW-48', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'صمام الجيش شواية ', 'sku' => 'RAW-49', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'صمام الجيش abd(من غير فونية', 'sku' => 'RAW-50', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'صمام طراش عادي', 'sku' => 'RAW-51', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'مرابط الجيش abd', 'sku' => 'RAW-52', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'عدسة', 'sku' => 'RAW-53', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'رشاش', 'sku' => 'RAW-54', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 1400],
            ['name' => 'فنشوري 90 الايطاليه', 'sku' => 'RAW-55', 'type' => 'raw_material ', 'unit' => 'طقم', 'min_stock' => 1400],
            ['name' => 'جلبة فنشوري جانبي(20 )', 'sku' => 'RAW-56', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'جلبة فنشوري وسط (22)', 'sku' => 'RAW-57', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'رومب 90 الايطاليه', 'sku' => 'RAW-58', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'نهاية مقبض تركي باكالايت', 'sku' => 'RAW-59', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'مقبض باب فرن 90 تركي ميلانو', 'sku' => 'RAW-60', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'بروفيل امامي 90', 'sku' => 'RAW-61', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'بروفيل خلفي 90', 'sku' => 'RAW-62', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'مفصلة بروفيل شمال', 'sku' => 'RAW-63', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'مفصلة بروفيل يمين', 'sku' => 'RAW-64', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ماتور شواية', 'sku' => 'RAW-65', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'سيخ شواية ', 'sku' => 'RAW-66', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ماسورة شواية سفلية (ضغط عالي فلير)', 'sku' => 'RAW-67', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ماسورة شواية علوية (ضغط عالي فلير)', 'sku' => 'RAW-68', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شواية حرف L', 'sku' => 'RAW-69', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شواية حرف I', 'sku' => 'RAW-70', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شواية حرف L(علوية)', 'sku' => 'RAW-71', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ماتور مروحة', 'sku' => 'RAW-72', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ريشة مروحة', 'sku' => 'RAW-73', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'صامولة مروحة', 'sku' => 'RAW-74', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'كفر مروحة', 'sku' => 'RAW-75', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'مفصلة باب 90 إيطالي', 'sku' => 'RAW-76', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 200],
            ['name' => 'قاعدة مفصلة 90', 'sku' => 'RAW-77', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'جوان باب فرن 90', 'sku' => 'RAW-78', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'بكالايت', 'sku' => 'RAW-79', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'بلية عين 90', 'sku' => 'RAW-80', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'ترملة', 'sku' => 'RAW-81', 'type' => 'raw_material ', 'unit' => 'كيس', 'min_stock' => 5],
            ['name' => 'شنكل', 'sku' => 'RAW-82', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'مرتكزة ', 'sku' => 'RAW-83', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'جلدة غطاء زجاج', 'sku' => 'RAW-84', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 200],
            ['name' => 'ارجل', 'sku' => 'RAW-85', 'type' => 'raw_material ', 'unit' => 'طقم', 'min_stock' => 100],
            ['name' => 'صوف', 'sku' => 'RAW-86', 'type' => 'raw_material ', 'unit' => 'لفة', 'min_stock' => 2],
            ['name' => 'شمبر ', 'sku' => 'RAW-87', 'type' => 'raw_material ', 'unit' => 'لفة', 'min_stock' => 2],
            ['name' => 'مسمار جلبة', 'sku' => 'RAW-88', 'type' => 'raw_material ', 'unit' => 'كيلو', 'min_stock' => 5],
            ['name' => 'مسمار رشاش', 'sku' => 'RAW-89', 'type' => 'raw_material ', 'unit' => 'كيلو', 'min_stock' => 5],
            ['name' => 'مسمار سطح', 'sku' => 'RAW-90', 'type' => 'raw_material ', 'unit' => 'علبة', 'min_stock' => 5],
            ['name' => 'لزق ابيض ورق', 'sku' => 'RAW-91', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 50],
            ['name' => 'شكرتون شفاف', 'sku' => 'RAW-92', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 50],
            ['name' => 'شكرتون كهرباء(اسود)', 'sku' => 'RAW-93', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 10],
            ['name' => 'تفلون', 'sku' => 'RAW-94', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 10],
            ['name' => 'تنر', 'sku' => 'RAW-95', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 3],
            ['name' => 'انبوبة سيليكون', 'sku' => 'RAW-96', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'سبراي', 'sku' => 'RAW-97', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 50],
            ['name' => 'شهادة ضمان', 'sku' => 'RAW-98', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 200],
            ['name' => 'استيكر مروحة', 'sku' => 'RAW-99', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 200],
            ['name' => 'كتالوج', 'sku' => 'RAW-100', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 200],
            ['name' => 'استرتش', 'sku' => 'RAW-101', 'type' => 'raw_material ', 'unit' => 'لفة', 'min_stock' => 3],
            ['name' => 'كرتونة 60*90 نورتك', 'sku' => 'RAW-102', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'كرتونة 60*80 نورتك', 'sku' => 'RAW-103', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'كرتونة 55*55 نورتك', 'sku' => 'RAW-104', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'قاعدة كرتونة 90', 'sku' => 'RAW-105', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 150],
            ['name' => 'قاعدة كرتونة 80', 'sku' => 'RAW-106', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 150],
            ['name' => 'قاعدة كرتونة 55', 'sku' => 'RAW-107', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 150],
            ['name' => 'رف شبك 90', 'sku' => 'RAW-108', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'استيكر غطاء ميلانو', 'sku' => 'RAW-109', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'استيكر باب ميلانو', 'sku' => 'RAW-110', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شهادة ضمان ميلانو', 'sku' => 'RAW-111', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'رومب 90 ميلانو', 'sku' => 'RAW-112', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فنشوري 55 يمين', 'sku' => 'RAW-113', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فنشوري 55 شمال', 'sku' => 'RAW-114', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'عدل امامي', 'sku' => 'RAW-115', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فنشوري 90 امامي يمين', 'sku' => 'RAW-116', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فنشوري 90 امامي شمال', 'sku' => 'RAW-117', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فنشوري 90 خلفي يمين', 'sku' => 'RAW-118', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فنشوري 90 خلفي شمال', 'sku' => 'RAW-119', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'فنشوري 90 وسط', 'sku' => 'RAW-120', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شواية علوية 90', 'sku' => 'RAW-121', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شواية سفلية 90', 'sku' => 'RAW-122', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شواية علوية 55', 'sku' => 'RAW-123', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'شواية سفلية 55', 'sku' => 'RAW-124', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'مسمار 1/2 *10 ابيض', 'sku' => 'RAW-125', 'type' => 'raw_material ', 'unit' => 'كيلو', 'min_stock' => 5],
            ['name' => 'مسمار 1/2 *10 اسود', 'sku' => 'RAW-126', 'type' => 'raw_material ', 'unit' => 'كيلو', 'min_stock' => 5],
            ['name' => 'مسمار 1/2 *10 اسود أكياس', 'sku' => 'RAW-127', 'type' => 'raw_material ', 'unit' => 'كيلو', 'min_stock' => 5],
            ['name' => 'مسمار وردة', 'sku' => 'RAW-128', 'type' => 'raw_material ', 'unit' => 'كيلو', 'min_stock' => 5],
            ['name' => 'مسمار مرتكزة', 'sku' => 'RAW-129', 'type' => 'raw_material ', 'unit' => 'كيلو', 'min_stock' => 5],
            ['name' => 'مسمار مقبض', 'sku' => 'RAW-130', 'type' => 'raw_material ', 'unit' => 'كيلو', 'min_stock' => 5],
            ['name' => 'جوان باب فرن 60 او 55', 'sku' => 'RAW-131', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'كفر مروحة شبك', 'sku' => 'RAW-132', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'انبوبة سيليكون اسود', 'sku' => 'RAW-133', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 20],
            ['name' => 'جوانتى', 'sku' => 'RAW-134', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 10],
            ['name' => 'سلاح قطر', 'sku' => 'RAW-135', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 5],
            ['name' => 'امير', 'sku' => 'RAW-136', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 5],
            ['name' => 'لقمة تك', 'sku' => 'RAW-137', 'type' => 'raw_material ', 'unit' => 'طقم', 'min_stock' => 5],
            ['name' => 'شريط لحام كهرباء', 'sku' => 'RAW-138', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 5],
            ['name' => 'حامل اوانى جانبي', 'sku' => 'RAW-139', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 200],
            ['name' => 'حامل اوانى وسط', 'sku' => 'RAW-140', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'زجاج باب 60*90 ميلانو', 'sku' => 'RAW-141', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'زجاج خارجي غطاء 60*90 ميلانو', 'sku' => 'RAW-142', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'زجاج غطاء 55*55', 'sku' => 'RAW-143', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'زجاج باب داخلي 60*90 نورتك', 'sku' => 'RAW-144', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'زجاج باب داخلي 60*80 نورتك', 'sku' => 'RAW-145', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'كرتون ميلانو 90', 'sku' => 'RAW-146', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 50],
            ['name' => 'كرتونة ميلانو 55*55', 'sku' => 'RAW-147', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'رف شبك 55*55', 'sku' => 'RAW-148', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'افيز كابل كهرباء', 'sku' => 'RAW-149', 'type' => 'raw_material ', 'unit' => 'كيس', 'min_stock' => 2],
            ['name' => 'مقبض عصب 90', 'sku' => 'RAW-150', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 50],
            ['name' => 'صاموله ضغط عالى', 'sku' => 'RAW-151', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 100],
            ['name' => 'لصق شفاف', 'sku' => 'RAW-152', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 20],
            ['name' => 'فوم اسطامبة ', 'sku' => 'RAW-153', 'type' => 'raw_material ', 'unit' => 'عدد', 'min_stock' => 50],
        ];

        // نقوم بتقسيم المصفوفة إلى أجزاء (Chunks) لتخفيف الضغط على الذاكرة وقاعدة البيانات أثناء الإدخال
        $chunks = array_chunk($products, 50);

        foreach ($chunks as $chunk) {
            DB::table('products')->insert($chunk);
        }
    }
}
